name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set tag var
      id: vars
      run: |
          echo ::set-output name=docker_tag::$(date +%s)

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag monapp:${{ steps.vars.outputs.docker_tag }}
    
    - name: Push to docker hub :latest
      run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin          
          docker tag monapp:${{ steps.vars.outputs.docker_tag }} pierrickm/monapp:latest
          docker tag monapp:${{ steps.vars.outputs.docker_tag }} pierrickm/monapp:${{ steps.vars.outputs.docker_tag }}
          docker push pierrickm/monapp:${{ steps.vars.outputs.docker_tag }}
          docker push pierrickm/monapp:latest
